# countries.py

COUNTRIES = [
    {"name": "Afghanistan", "flag_url": "https://flagcdn.com/w320/af.png", "continent": "Asia", "capital": "Kabul"},
    {"name": "Albania", "flag_url": "https://flagcdn.com/w320/al.png", "continent": "Europe", "capital": "Tirana"},
    {"name": "Algeria", "flag_url": "https://flagcdn.com/w320/dz.png", "continent": "Africa", "capital": "Alger"},
    {"name": "Andorra", "flag_url": "https://flagcdn.com/w320/ad.png", "continent": "Europe", "capital": "Andorra la Vella"},
    {"name": "Angola", "flag_url": "https://flagcdn.com/w320/ao.png", "continent": "Africa", "capital": "Luanda"},
    {"name": "Antigua and Barbuda", "flag_url": "https://flagcdn.com/w320/ag.png", "continent": "North America", "capital": "Saint John's"},
    {"name": "Argentina", "flag_url": "https://flagcdn.com/w320/ar.png", "continent": "South America", "capital": "Buenos Aires"},
    {"name": "Armenia", "flag_url": "https://flagcdn.com/w320/am.png", "continent": "Asia", "capital": "Yerevan"},
    {"name": "Australia", "flag_url": "https://flagcdn.com/w320/au.png", "continent": "Oceania", "capital": "Canberra"},
    {"name": "Austria", "flag_url": "https://flagcdn.com/w320/at.png", "continent": "Europe", "capital": "Wien"},
    {"name": "Azerbaijan", "flag_url": "https://flagcdn.com/w320/az.png", "continent": "Asia", "capital": "Baku"},
    {"name": "Bahamas", "flag_url": "https://flagcdn.com/w320/bs.png", "continent": "North America", "capital": "Nassau"},
    {"name": "Bahrain", "flag_url": "https://flagcdn.com/w320/bh.png", "continent": "Asia", "capital": "al-Manama"},
    {"name": "Bangladesh", "flag_url": "https://flagcdn.com/w320/bd.png", "continent": "Asia", "capital": "Dhaka"},
    {"name": "Barbados", "flag_url": "https://flagcdn.com/w320/bb.png", "continent": "North America", "capital": "Bridgetown"},
    {"name": "Belarus", "flag_url": "https://flagcdn.com/w320/by.png", "continent": "Europe", "capital": "Minsk"},
    {"name": "Belgium", "flag_url": "https://flagcdn.com/w320/be.png", "continent": "Europe", "capital": "Bruxelles [Brussel]"},
    {"name": "Belize", "flag_url": "https://flagcdn.com/w320/bz.png", "continent": "North America", "capital": "Belmopan"},
    {"name": "Benin", "flag_url": "https://flagcdn.com/w320/bj.png", "continent": "Africa", "capital": "Porto-Novo"},
    {"name": "Bhutan", "flag_url": "https://flagcdn.com/w320/bt.png", "continent": "Asia", "capital": "Thimphu"},
    {"name": "Bolivia", "flag_url": "https://flagcdn.com/w320/bo.png", "continent": "South America", "capital": "La Paz"},
    {"name": "Bosnia and Herzegovina", "flag_url": "https://flagcdn.com/w320/ba.png", "continent": "Europe", "capital": "Sarajevo"},
    {"name": "Botswana", "flag_url": "https://flagcdn.com/w320/bw.png", "continent": "Africa", "capital": "Gaborone"},
    {"name": "Brazil", "flag_url": "https://flagcdn.com/w320/br.png", "continent": "South America", "capital": "Brasilia"},
    {"name": "Brunei", "flag_url": "https://flagcdn.com/w320/bn.png", "continent": "Asia", "capital": "Bandar Seri Begawan"},
    {"name": "Bulgaria", "flag_url": "https://flagcdn.com/w320/bg.png", "continent": "Europe", "capital": "Sofia"},
    {"name": "Burkina Faso", "flag_url": "https://flagcdn.com/w320/bf.png", "continent": "Africa", "capital": "Ouagadougou"},
    {"name": "Burundi", "flag_url": "https://flagcdn.com/w320/bi.png", "continent": "Africa", "capital": "Bujumbura"},
    {"name": "Cabo Verde", "flag_url": "https://flagcdn.com/w320/cv.png", "continent": "Africa", "capital": "Praia"},
    {"name": "Cambodia", "flag_url": "https://flagcdn.com/w320/kh.png", "continent": "Asia", "capital": "Phnom Penh"},
    {"name": "Cameroon", "flag_url": "https://flagcdn.com/w320/cm.png", "continent": "Africa", "capital": "Yaounde"},
    {"name": "Canada", "flag_url": "https://flagcdn.com/w320/ca.png", "continent": "North America", "capital": "Ottawa"},
    {"name": "Central African Republic", "flag_url": "https://flagcdn.com/w320/cf.png", "continent": "Africa", "capital": "Bangui"},
    {"name": "Chad", "flag_url": "https://flagcdn.com/w320/td.png", "continent": "Africa", "capital": "N'Djamena"},
    {"name": "Chile", "flag_url": "https://flagcdn.com/w320/cl.png", "continent": "South America", "capital": "Santiago de Chile"},
    {"name": "China", "flag_url": "https://flagcdn.com/w320/cn.png", "continent": "Asia", "capital": "Beijing"},
    {"name": "Colombia", "flag_url": "https://flagcdn.com/w320/co.png", "continent": "South America", "capital": "Bogota"},
    {"name": "Comoros", "flag_url": "https://flagcdn.com/w320/km.png", "continent": "Africa", "capital": "Moroni"},
    {"name": "Congo (Brazzaville)", "flag_url": "https://flagcdn.com/w320/cg.png", "continent": "Africa", "capital": "Kinshasa"},
    {"name": "Congo (Kinshasa)", "flag_url": "https://flagcdn.com/w320/cd.png", "continent": "Africa", "capital": "Kinshasa"},
    {"name": "Costa Rica", "flag_url": "https://flagcdn.com/w320/cr.png", "continent": "North America", "capital": "San José"},
    {"name": "Croatia", "flag_url": "https://flagcdn.com/w320/hr.png", "continent": "Europe", "capital": "Zagreb"},
    {"name": "Cuba", "flag_url": "https://flagcdn.com/w320/cu.png", "continent": "North America", "capital": "La Habana"},
    {"name": "Cyprus", "flag_url": "https://flagcdn.com/w320/cy.png", "continent": "Asia", "capital": "Nicosia"},
    {"name": "Czechia", "flag_url": "https://flagcdn.com/w320/cz.png", "continent": "Europe", "capital": "Praha"},
    {"name": "Denmark", "flag_url": "https://flagcdn.com/w320/dk.png", "continent": "Europe", "capital": "Copenhagen"},
    {"name": "Djibouti", "flag_url": "https://flagcdn.com/w320/dj.png", "continent": "Africa", "capital": "Djibouti"},
    {"name": "Dominica", "flag_url": "https://flagcdn.com/w320/dm.png", "continent": "North America", "capital": "Roseau"},
    {"name": "Dominican Republic", "flag_url": "https://flagcdn.com/w320/do.png", "continent": "North America", "capital": "Santo Domingo de Guzm"},
    {"name": "Ecuador", "flag_url": "https://flagcdn.com/w320/ec.png", "continent": "South America", "capital": "Quito"},
    {"name": "Egypt", "flag_url": "https://flagcdn.com/w320/eg.png", "continent": "Africa", "capital": "Cairo"},
    {"name": "El Salvador", "flag_url": "https://flagcdn.com/w320/sv.png", "continent": "North America", "capital": "San Salvador"},
    {"name": "Equatorial Guinea", "flag_url": "https://flagcdn.com/w320/gq.png", "continent": "Africa", "capital": "Malabo"},
    {"name": "Eritrea", "flag_url": "https://flagcdn.com/w320/er.png", "continent": "Africa", "capital": "Asmara"},
    {"name": "Estonia", "flag_url": "https://flagcdn.com/w320/ee.png", "continent": "Europe", "capital": "Tallinn"},
    {"name": "Eswatini", "flag_url": "https://flagcdn.com/w320/sz.png", "continent": "Africa", "capital": "Mbabane"},
    {"name": "Ethiopia", "flag_url": "https://flagcdn.com/w320/et.png", "continent": "Africa", "capital": "Addis Abeba"},
    {"name": "Fiji", "flag_url": "https://flagcdn.com/w320/fj.png", "continent": "Oceania", "capital": "Suva"},
    {"name": "Finland", "flag_url": "https://flagcdn.com/w320/fi.png", "continent": "Europe", "capital": "Helsinki [Helsingfors]"},
    {"name": "France", "flag_url": "https://flagcdn.com/w320/fr.png", "continent": "Europe", "capital": "Paris"},
    {"name": "Gabon", "flag_url": "https://flagcdn.com/w320/ga.png", "continent": "Africa", "capital": "Libreville"},
    {"name": "Gambia", "flag_url": "https://flagcdn.com/w320/gm.png", "continent": "Africa", "capital": "Banjul"},
    {"name": "Georgia", "flag_url": "https://flagcdn.com/w320/ge.png", "continent": "Asia", "capital": "Tbilisi"},
    {"name": "Ghana", "flag_url": "https://flagcdn.com/w320/gh.png", "continent": "Africa", "capital": "Accra"},
    {"name": "Greece", "flag_url": "https://flagcdn.com/w320/gr.png", "continent": "Europe", "capital": "Athenai"},
    {"name": "Grenada", "flag_url": "https://flagcdn.com/w320/gd.png", "continent": "North America", "capital": "Saint George's"},
    {"name": "Guatemala", "flag_url": "https://flagcdn.com/w320/gt.png", "continent": "North America", "capital": "Ciudad de Guatemala"},
    {"name": "Guinea", "flag_url": "https://flagcdn.com/w320/gn.png", "continent": "Africa", "capital": "Conakry"},
    {"name": "Guinea-Bissau", "flag_url": "https://flagcdn.com/w320/gw.png", "continent": "Africa", "capital": "Bissau"},
    {"name": "Guyana", "flag_url": "https://flagcdn.com/w320/gy.png", "continent": "South America", "capital": "Georgetown"},
    {"name": "Haiti", "flag_url": "https://flagcdn.com/w320/ht.png", "continent": "North America", "capital": "Port-au-Prince"},
    {"name": "Honduras", "flag_url": "https://flagcdn.com/w320/hn.png", "continent": "North America", "capital": "Tegucigalpa"},
    {"name": "Hungary", "flag_url": "https://flagcdn.com/w320/hu.png", "continent": "Europe", "capital": "Budapest"},
    {"name": "Iceland", "flag_url": "https://flagcdn.com/w320/is.png", "continent": "Europe", "capital": "Reykjavík"},
    {"name": "India", "flag_url": "https://flagcdn.com/w320/in.png", "continent": "Asia", "capital": "New Delhi"},
    {"name": "Indonesia", "flag_url": "https://flagcdn.com/w320/id.png", "continent": "Asia", "capital": "Jakarta"},
    {"name": "Iran", "flag_url": "https://flagcdn.com/w320/ir.png", "continent": "Asia", "capital": "Tehran"},
    {"name": "Iraq", "flag_url": "https://flagcdn.com/w320/iq.png", "continent": "Asia", "capital": "Baghdad"},
    {"name": "Ireland", "flag_url": "https://flagcdn.com/w320/ie.png", "continent": "Europe", "capital": "Dublin"},
    {"name": "Israel", "flag_url": "https://flagcdn.com/w320/il.png", "continent": "Asia", "capital": "Jerusalem"},
    {"name": "Italy", "flag_url": "https://flagcdn.com/w320/it.png", "continent": "Europe", "capital": "Roma"},
    {"name": "Ivory Coast", "flag_url": "https://flagcdn.com/w320/ci.png", "continent": "Africa", "capital": "Yamoussoukro"},
    {"name": "Jamaica", "flag_url": "https://flagcdn.com/w320/jm.png", "continent": "North America", "capital": "Kingston"},
    {"name": "Japan", "flag_url": "https://flagcdn.com/w320/jp.png", "continent": "Asia", "capital": "Tokyo"},
    {"name": "Jordan", "flag_url": "https://flagcdn.com/w320/jo.png", "continent": "Asia", "capital": "Amman"},
    {"name": "Kazakhstan", "flag_url": "https://flagcdn.com/w320/kz.png", "continent": "Asia", "capital": "Astana"},
    {"name": "Kenya", "flag_url": "https://flagcdn.com/w320/ke.png", "continent": "Africa", "capital": "Nairobi"},
    {"name": "Kiribati", "flag_url": "https://flagcdn.com/w320/ki.png", "continent": "Oceania", "capital": "Bairiki"},
    {"name": "Kuwait", "flag_url": "https://flagcdn.com/w320/kw.png", "continent": "Asia", "capital": "Kuwait"},
    {"name": "Kyrgyzstan", "flag_url": "https://flagcdn.com/w320/kg.png", "continent": "Asia", "capital": "Bishkek"},
    {"name": "Laos", "flag_url": "https://flagcdn.com/w320/la.png", "continent": "Asia", "capital": "Vientiane"},
    {"name": "Latvia", "flag_url": "https://flagcdn.com/w320/lv.png", "continent": "Europe", "capital": "Riga"},
    {"name": "Lebanon", "flag_url": "https://flagcdn.com/w320/lb.png", "continent": "Asia", "capital": "Beirut"},
    {"name": "Lesotho", "flag_url": "https://flagcdn.com/w320/ls.png", "continent": "Africa", "capital": "Maseru"},
    {"name": "Liberia", "flag_url": "https://flagcdn.com/w320/lr.png", "continent": "Africa", "capital": "Monrovia"},
    {"name": "Libya", "flag_url": "https://flagcdn.com/w320/ly.png", "continent": "Africa", "capital": "Tripoli"},
    {"name": "Liechtenstein", "flag_url": "https://flagcdn.com/w320/li.png", "continent": "Europe", "capital": "Vaduz"},
    {"name": "Lithuania", "flag_url": "https://flagcdn.com/w320/lt.png", "continent": "Europe", "capital": "Vilnius"},
    {"name": "Luxembourg", "flag_url": "https://flagcdn.com/w320/lu.png", "continent": "Europe", "capital": "Luxembourg [Luxemburg/L"},
    {"name": "Madagascar", "flag_url": "https://flagcdn.com/w320/mg.png", "continent": "Africa", "capital": "Antananarivo"},
    {"name": "Malawi", "flag_url": "https://flagcdn.com/w320/mw.png", "continent": "Africa", "capital": "Lilongwe"},
    {"name": "Malaysia", "flag_url": "https://flagcdn.com/w320/my.png", "continent": "Asia", "capital": "Kuala Lumpur"},
    {"name": "Maldives", "flag_url": "https://flagcdn.com/w320/mv.png", "continent": "Asia", "capital": "Male"},
    {"name": "Mali", "flag_url": "https://flagcdn.com/w320/ml.png", "continent": "Africa", "capital": "Bamako"},
    {"name": "Malta", "flag_url": "https://flagcdn.com/w320/mt.png", "continent": "Europe", "capital": "Valletta"},
    {"name": "Marshall Islands", "flag_url": "https://flagcdn.com/w320/mh.png", "continent": "Oceania", "capital": "Dalap-Uliga-Darrit"},
    {"name": "Mauritania", "flag_url": "https://flagcdn.com/w320/mr.png", "continent": "Africa", "capital": "Nouakchott"},
    {"name": "Mauritius", "flag_url": "https://flagcdn.com/w320/mu.png", "continent": "Africa", "capital": "Port-Louis"},
    {"name": "Mexico", "flag_url": "https://flagcdn.com/w320/mx.png", "continent": "North America", "capital": "Ciudad de M"},
    {"name": "Micronesia", "flag_url": "https://flagcdn.com/w320/fm.png", "continent": "Oceania", "capital": "Palikir"},
    {"name": "Moldova", "flag_url": "https://flagcdn.com/w320/md.png", "continent": "Europe", "capital": "Chisinau"},
    {"name": "Monaco", "flag_url": "https://flagcdn.com/w320/mc.png", "continent": "Europe", "capital": "Monaco-Ville"},
    {"name": "Mongolia", "flag_url": "https://flagcdn.com/w320/mn.png", "continent": "Asia", "capital": "Ulan Bator"},
    {"name": "Montenegro", "flag_url": "https://flagcdn.com/w320/me.png", "continent": "Europe", "capital": "Podgorica"},
    {"name": "Morocco", "flag_url": "https://flagcdn.com/w320/ma.png", "continent": "Africa", "capital": "Rabat"},
    {"name": "Mozambique", "flag_url": "https://flagcdn.com/w320/mz.png", "continent": "Africa", "capital": "Maputo"},
    {"name": "Myanmar", "flag_url": "https://flagcdn.com/w320/mm.png", "continent": "Asia", "capital": "Rangoon (Yangon)"},
    {"name": "Namibia", "flag_url": "https://flagcdn.com/w320/na.png", "continent": "Africa", "capital": "Windhoek"},
    {"name": "Nauru", "flag_url": "https://flagcdn.com/w320/nr.png", "continent": "Oceania", "capital": "Yaren"},
    {"name": "Nepal", "flag_url": "https://flagcdn.com/w320/np.png", "continent": "Asia", "capital": "Kathmandu"},
    {"name": "Netherlands", "flag_url": "https://flagcdn.com/w320/nl.png", "continent": "Europe", "capital": "Amsterdam"},
    {"name": "New Zealand", "flag_url": "https://flagcdn.com/w320/nz.png", "continent": "Oceania", "capital": "Wellington"},
    {"name": "Nicaragua", "flag_url": "https://flagcdn.com/w320/ni.png", "continent": "North America", "capital": "Managua"},
    {"name": "Niger", "flag_url": "https://flagcdn.com/w320/ne.png", "continent": "Africa", "capital": "Niamey"},
    {"name": "Nigeria", "flag_url": "https://flagcdn.com/w320/ng.png", "continent": "Africa", "capital": "Abuja"},
    {"name": "North Korea", "flag_url": "https://flagcdn.com/w320/kp.png", "continent": "Asia", "capital": "Pyongyang"},
    {"name": "North Macedonia", "flag_url": "https://flagcdn.com/w320/mk.png", "continent": "Europe", "capital": "Skopje"},
    {"name": "Norway", "flag_url": "https://flagcdn.com/w320/no.png", "continent": "Europe", "capital": "Oslo"},
    {"name": "Oman", "flag_url": "https://flagcdn.com/w320/om.png", "continent": "Asia", "capital": "Masqat"},
    {"name": "Pakistan", "flag_url": "https://flagcdn.com/w320/pk.png", "continent": "Asia", "capital": "Islamabad"},
    {"name": "Palau", "flag_url": "https://flagcdn.com/w320/pw.png", "continent": "Oceania", "capital": "Koror"},
    {"name": "Palestine", "flag_url": "https://flagcdn.com/w320/ps.png", "continent": "Asia", "capital": "Gaza"},
    {"name": "Panama", "flag_url": "https://flagcdn.com/w320/pa.png", "continent": "North America", "capital": "Ciudad de Panamá"},
    {"name": "Papua New Guinea", "flag_url": "https://flagcdn.com/w320/pg.png", "continent": "Oceania", "capital": "Port Moresby"},
    {"name": "Paraguay", "flag_url": "https://flagcdn.com/w320/py.png", "continent": "South America", "capital": "Asunción"},
    {"name": "Peru", "flag_url": "https://flagcdn.com/w320/pe.png", "continent": "South America", "capital": "Lima"},
    {"name": "Philippines", "flag_url": "https://flagcdn.com/w320/ph.png", "continent": "Asia", "capital": "Manila"},
    {"name": "Poland", "flag_url": "https://flagcdn.com/w320/pl.png", "continent": "Europe", "capital": "Warszawa"},
    {"name": "Portugal", "flag_url": "https://flagcdn.com/w320/pt.png", "continent": "Europe", "capital": "Lisboa"},
    {"name": "Qatar", "flag_url": "https://flagcdn.com/w320/qa.png", "continent": "Asia", "capital": "Doha"},
    {"name": "Romania", "flag_url": "https://flagcdn.com/w320/ro.png", "continent": "Europe", "capital": "Bucuresti"},
    {"name": "Russia", "flag_url": "https://flagcdn.com/w320/ru.png", "continent": "Europe", "capital": "Moscow"},
    {"name": "Rwanda", "flag_url": "https://flagcdn.com/w320/rw.png", "continent": "Africa", "capital": "Kigali"},
    {"name": "Saint Kitts and Nevis", "flag_url": "https://flagcdn.com/w320/kn.png", "continent": "North America", "capital": "Basseterre"},
    {"name": "Saint Lucia", "flag_url": "https://flagcdn.com/w320/lc.png", "continent": "North America", "capital": "Castries"},
    {"name": "Saint Vincent and the Grenadines", "flag_url": "https://flagcdn.com/w320/vc.png", "continent": "North America", "capital": "Kingstown"},
    {"name": "Samoa", "flag_url": "https://flagcdn.com/w320/ws.png", "continent": "Oceania", "capital": "Apia"},
    {"name": "San Marino", "flag_url": "https://flagcdn.com/w320/sm.png", "continent": "Europe", "capital": "San Marino"},
    {"name": "Sao Tome and Principe", "flag_url": "https://flagcdn.com/w320/st.png", "continent": "Africa", "capital": "São Tomé"},
    {"name": "Saudi Arabia", "flag_url": "https://flagcdn.com/w320/sa.png", "continent": "Asia", "capital": "Riyadh"},
    {"name": "Senegal", "flag_url": "https://flagcdn.com/w320/sn.png", "continent": "Africa", "capital": "Dakar"},
    {"name": "Serbia", "flag_url": "https://flagcdn.com/w320/rs.png", "continent": "Europe", "capital": "Belgrade"},
    {"name": "Seychelles", "flag_url": "https://flagcdn.com/w320/sc.png", "continent": "Africa", "capital": "Victoria"},
    {"name": "Sierra Leone", "flag_url": "https://flagcdn.com/w320/sl.png", "continent": "Africa", "capital": "Freetown"},
    {"name": "Singapore", "flag_url": "https://flagcdn.com/w320/sg.png", "continent": "Asia", "capital": "Singapore"},
    {"name": "Slovakia", "flag_url": "https://flagcdn.com/w320/sk.png", "continent": "Europe", "capital": "Bratislava"},
    {"name": "Slovenia", "flag_url": "https://flagcdn.com/w320/si.png", "continent": "Europe", "capital": "Ljubljana"},
    {"name": "Solomon Islands", "flag_url": "https://flagcdn.com/w320/sb.png", "continent": "Oceania", "capital": "Honiara"},
    {"name": "Somalia", "flag_url": "https://flagcdn.com/w320/so.png", "continent": "Africa", "capital": "Mogadishu"},
    {"name": "South Africa", "flag_url": "https://flagcdn.com/w320/za.png", "continent": "Africa", "capital": "Pretoria"},
    {"name": "South Sudan", "flag_url": "https://flagcdn.com/w320/ss.png", "continent": "Africa", "capital": "Juba"},
    {"name": "Spain", "flag_url": "https://flagcdn.com/w320/es.png", "continent": "Europe", "capital": "Madrid"},
    {"name": "Sri Lanka", "flag_url": "https://flagcdn.com/w320/lk.png", "continent": "Asia", "capital": "Colombo, Sri Jayawardenepura Kotte"},
    {"name": "Sudan", "flag_url": "https://flagcdn.com/w320/sd.png", "continent": "Africa", "capital": "Khartum"},
    {"name": "Suriname", "flag_url": "https://flagcdn.com/w320/sr.png", "continent": "South America", "capital": "Paramaribo"},
    {"name": "Sweden", "flag_url": "https://flagcdn.com/w320/se.png", "continent": "Europe", "capital": "Stockholm"},
    {"name": "Switzerland", "flag_url": "https://flagcdn.com/w320/ch.png", "continent": "Europe", "capital": "Bern"},
    {"name": "Syria", "flag_url": "https://flagcdn.com/w320/sy.png", "continent": "Asia", "capital": "Damascus"},
    {"name": "Tajikistan", "flag_url": "https://flagcdn.com/w320/tj.png", "continent": "Asia", "capital": "Dushanbe"},
    {"name": "Tanzania", "flag_url": "https://flagcdn.com/w320/tz.png", "continent": "Africa", "capital": "Dodoma"},
    {"name": "Thailand", "flag_url": "https://flagcdn.com/w320/th.png", "continent": "Asia", "capital": "Bangkok"},
    {"name": "Timor-Leste", "flag_url": "https://flagcdn.com/w320/tl.png", "continent": "Asia", "capital": "Dili"},
    {"name": "Togo", "flag_url": "https://flagcdn.com/w320/tg.png", "continent": "Africa", "capital": "Lomé"},
    {"name": "Tonga", "flag_url": "https://flagcdn.com/w320/to.png", "continent": "Oceania", "capital": "Nuku'alofa"},
    {"name": "Trinidad and Tobago", "flag_url": "https://flagcdn.com/w320/tt.png", "continent": "North America", "capital": "Port-of-Spain"},
    {"name": "Tunisia", "flag_url": "https://flagcdn.com/w320/tn.png", "continent": "Africa", "capital": "Tunis"},
    {"name": "Turkey", "flag_url": "https://flagcdn.com/w320/tr.png", "continent": "Asia", "capital": "Ankara"},
    {"name": "Turkmenistan", "flag_url": "https://flagcdn.com/w320/tm.png", "continent": "Asia", "capital": "Ashgabat"},
    {"name": "Tuvalu", "flag_url": "https://flagcdn.com/w320/tv.png", "continent": "Oceania", "capital": "Funafuti"},
    {"name": "Uganda", "flag_url": "https://flagcdn.com/w320/ug.png", "continent": "Africa", "capital": "Kampala"},
    {"name": "Ukraine", "flag_url": "https://flagcdn.com/w320/ua.png", "continent": "Europe", "capital": "Kyiv"},
    {"name": "United Arab Emirates", "flag_url": "https://flagcdn.com/w320/ae.png", "continent": "Asia", "capital": "Abu Dhabi"},
    {"name": "United Kingdom", "flag_url": "https://flagcdn.com/w320/gb.png", "continent": "Europe", "capital": "London"},
    {"name": "United States", "flag_url": "https://flagcdn.com/w320/us.png", "continent": "North America", "capital": "Washington"},
    {"name": "Uruguay", "flag_url": "https://flagcdn.com/w320/uy.png", "continent": "South America", "capital": "Montevideo"},
    {"name": "Uzbekistan", "flag_url": "https://flagcdn.com/w320/uz.png", "continent": "Asia", "capital": "Toskent"},
    {"name": "Vanuatu", "flag_url": "https://flagcdn.com/w320/vu.png", "continent": "Oceania", "capital": "Port-Vila"},
    {"name": "Vatican City", "flag_url": "https://flagcdn.com/w320/va.png", "continent": "Europe", "capital": "Citt"},
    {"name": "Venezuela", "flag_url": "https://flagcdn.com/w320/ve.png", "continent": "South America", "capital": "Caracas"},
    {"name": "Vietnam", "flag_url": "https://flagcdn.com/w320/vn.png", "continent": "Asia", "capital": "Hanoi"},
    {"name": "Yemen", "flag_url": "https://flagcdn.com/w320/ye.png", "continent": "Asia", "capital": "Sanaa"},
    {"name": "Zambia", "flag_url": "https://flagcdn.com/w320/zm.png", "continent": "Africa", "capital": "Lusaka"},
    {"name": "Zimbabwe", "flag_url": "https://flagcdn.com/w320/zw.png", "continent": "Africa", "capital": "Harare"},
]
